### ISSUE TITLE
Publish on packagist

### ISSUE THREAD

**Issue by pgampe** [TYPO3/Fluid.SchemaGenerator#1]
This package is currently not listed on packagist. Please check and add it there if possible.

**Comment by NamelessCoder** [comment]
Hi Philipp - I'd love to do this, but there are a couple of potential blockers:

* We can place it in `typo3` or `typo3fluid` namespaces but it hasn't been decided which
* I offered to transfer ownership to `TYPO3Fluid` github organisation but this org no longer is relevant, so it should be in `TYPO3` instead?

I would be quite happy to put this in its final place - which of the places do you think we should use? I'm leaning towards putting this in `TYPO3` GitHub org and `typo3` packagist vendor namespace, since the final goal is to put Fluid itself into `typo3` on packagist (it is already in `TYPO3` on GitHub).

**Comment by pgampe** [comment]
Well I agree to putting to wherever the `fluid` package is. Thus `typo3` then.

**Comment by NamelessCoder** [comment]
@pgampe So if I go ahead now and 1) update the composer name, 2) update the PHP namespace and 3) transfer this to `TYPO3` on GitHub you will a) give me maintenance privileges on the transferred repo, b) register it on packagist with the transferred repo URL and give me maintenance privileges on the packagist repo?

If so, I am ready to go! :)

**Comment by NamelessCoder** [comment]
Version 2.0.0 is tagged after converting the namespaces. Any time you are ready I can transfer ownership to TYPO3 organisation.

Will need Packagist and Travis hooks restored (and I forgot to say I'd also like maintenance privileges on the Travis setup)

**Comment by pgampe** [comment]
I am sorry, I am not a member of the TYPO3 organization (just themes and t3o).

**Comment by NamelessCoder** [comment]
No worries :)

**Comment by smichaelsen** [comment]
Any progress on this? I guess the installation guide in the README file should be adapted then. 

    composer require typo3/fluid-schema-generator

This doesn't work..

**Comment by NamelessCoder** [comment]
Ping @bmack - I think you've got the superpowers we need for this ;)

**Comment by georg-tiefenbrunn** [comment]
Ping @bmack - We strongly and absolutely need your superpowers for this ;)

**Comment by bmack** [comment]
Thanks for pinging again. This is taken care of now.

**Comment by georg-tiefenbrunn** [comment]
Thank you guys!
