### ISSUE TITLE
Allow use from global installation

### ISSUE THREAD

**Issue by pgampe** [TYPO3/Fluid.SchemaGenerator#2]
Use the current `pwd` as the base for the `TYPO3` installation.

This would allow to install the script in the global composer location (usually `~/.composer/bin`) and use it from there without the need to put it into the local composer configuration.

**Comment by NamelessCoder** [comment]
The schema generator is intended to work for any framework, not just TYPO3. Using `pwd` as base path means we either have to assume the vendor dir location or parse the composer.json manifest in `pwd` path to determine vendor dir.

There's also a lot of good to be said about keeping this as a `--dev` dependency in the project itself, since it does depend on the Fluid version you use.

**Comment by pgampe** [comment]
ok then

**Comment by NamelessCoder** [comment]
If we need to change the lookup of paths to some better alternative that's fine with me, but we should start from `__FILE__` or `__DIR__` and work backwards.
