### ISSUE TITLE
Is it possible to support older Fluid / TYPO3 versions?

### ISSUE THREAD

**Issue by DanielSiepmann** [TYPO3/Fluid.SchemaGenerator#8]
We get the request to provide a ViewHelper reference for TYPO3 Versions < 9.5.

While playing around, it looks like the main issue is dependency injection within sysext:fluid. When trying to adjust this, to also work without DI, I receive further issues regarding TYPO3 internal caching.

**Comment by NamelessCoder** [comment]
Just copying Slack reply to here:

> re: generating references for older versions, there are a couple of things to know:
> Only 9.x is 100% free from use of render() method arguments

> Render method arguments were deprecated on 8.7 and the core *should* be free of them, save for any overrides. Third-party extensions that have max 8.7 support do tend to still contain them.
> Render method arguments become part of the ArgumentDefinitions on TYPO3 versions that support this. The definitions and sequence of arguments are read by using Reflection, which in turn demands the extbase_reflection cache

The short version is that it is possible, but because Reflection is used and this requires a cache, there is so much environment that is not feasible to do through the included CLI command. What you would need to do is:

* Create a CLI command native to the TYPO3 version which means you would have the right environment.
* From that CLI command, call https://github.com/TYPO3/Fluid.SchemaGenerator/blob/master/src/SchemaGenerator.php#L41 and provide a closure that uses `ObjectManager->get()` to create ViewHelper class instances

This approach would be the same for any third party application. Lastly, there is a historical collection of TYPO3 CMS Fluid XSD files which can be used in IDEs and to generate online docs: https://fluidtypo3.org/schemas/
